### ISSUE TITLE
Question: Why is the sample http listener not returning an empty HTTP 200 response

### ISSUE THREAD

**Issue by finrod2002** [paypal/ipn-code-samples#6]
On 

https://developer.paypal.com/webapps/developer/docs/classic/ipn/integration-guide/IPNIntro/

it is stated that

"Your listener returns an empty HTTP 200 response"

before 

"Your listener HTTP POSTs the complete, unaltered message back to PayPal."

Why is the sample PHP code directly posting the complete, unaltered message back to PayPal instead of first sending the empty HTTP 200 response? Or am I just missing something?

Thanks,
Luca

**Comment by raheelkhan** [comment]
I am also wondering why they are not sending empty 200

**Comment by pp-randy** [comment]
In my experience problems starts coming up when a lot of business processing occurs in the script before a 200 is provided.  I would recommend to return a 200 sooner if IPN is timing out to your listener, causing IPN to resend. However, you might have some situations when you would want an automatic resend which won't happen with an immediate http 200 status since that tells PayPal that the IPN was sent correctly.  Making sure you have the IPN data you need is important and leveraging an automatic resend every once in awhile due to a possible storage issue on your end might not be a bad thing to consider.
